[package]
name = "superdev"
version = "0.1.0"
description = "SuperDev desktop application"
authors = ["SuperDev contributors"]
license = "MIT"
repository = "https://github.com/Xsxdot/super-dev"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9.12"
tauri-plugin-autostart = "2.5.1"
